### ISSUE TITLE
Local build on mac: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by claj** [aws/aws-codebuild-docker-images#75]
On MacOS High Sierra 10.13.4 i did pull latest to avoid another mac issue 

`docker pull amazon/aws-codebuild-local:latest --disable-content-trust=false`

I downloaded and built the jre8-image from here.

I get the following stacktrace. I simply have no idea what could be wrong.

```
$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e "IMAGE_NAME=aws/codebuild/java:openjdk-8" -e "ARTIFACTS=/Users/fauxuser/code/artifacts" -e "SOURCE=/Users/fauxuser/code/project" amazon/aws-codebuild-local
Removing agentresources_build_1 ... done
Removing agentresources_agent_1 ... done
Removing network agentresources_default
Removing volume agentresources_user_volume
Removing volume agentresources_source_volume
Creating network "agentresources_default" with the default driver
Creating volume "agentresources_user_volume" with local driver
Creating volume "agentresources_source_volume" with local driver
Creating agentresources_agent_1 ... 
Creating agentresources_agent_1 ... done
Creating agentresources_build_1 ... 
Creating agentresources_build_1 ... done
Attaching to agentresources_agent_1, agentresources_build_1
agent_1  | [Container] 2018/05/25 09:06:00 Waiting for agent ping
agent_1  | [Container] 2018/05/25 09:06:00 Waiting for DOWNLOAD_SOURCE
agent_1  | [Container] 2018/05/25 09:07:04 Phase is DOWNLOAD_SOURCE
agent_1  | [Container] 2018/05/25 09:07:07 CODEBUILD_SRC_DIR=/codebuild/output/src942176067/src
agent_1  | [Container] 2018/05/25 09:07:07 YAML location is /codebuild/output/src942176067/src/buildspec.yml
agent_1  | [Container] 2018/05/25 09:07:07 Processing environment variables
agent_1  | [Container] 2018/05/25 09:07:07 Moving to directory /codebuild/output/src942176067/src
build_1  | panic: runtime error: invalid memory address or nil pointer dereference
build_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7b672a]
build_1  | 
build_1  | goroutine 1 [running]:
build_1  | amazon/aws/codebuild/container/executor/state/cache.NewCacheImpl(0xc4200c3080, 0xc4200e8ce8, 0xc4200144e0, 0x22, 0xc4201a4448, 0x5, 0xc33920, 0xc4201a0048, 0xc4200144e0, 0x22, ...)
build_1  | 	/home/stangers/AgentWork/src/CoFaContainerBootstrap/src/amazon/aws/codebuild/container/executor/state/cache/impl.go:25 +0xda
build_1  | amazon/aws/codebuild/container/executor/state.(*mainState).downloadCache(0xc42014a100, 0x0, 0x0)
build_1  | 	/home/stangers/AgentWork/src/CoFaContainerBootstrap/src/amazon/aws/codebuild/container/executor/state/cache.go:30 +0x386
build_1  | amazon/aws/codebuild/container/executor/state.(*mainState).Run.func12(0xc42014a100, 0x0, 0x0)
build_1  | 	/home/stangers/AgentWork/src/CoFaContainerBootstrap/src/amazon/aws/codebuild/container/executor/state/run.go:22 +0x2b
build_1  | amazon/aws/codebuild/container/executor/state.(*mainState).Run(0xc42014a100, 0x0, 0x966d2a)
build_1  | 	/home/stangers/AgentWork/src/CoFaContainerBootstrap/src/amazon/aws/codebuild/container/executor/state/run.go:29 +0x156
build_1  | main.main()
build_1  | 	/home/stangers/AgentWork/src/CoFaContainerBootstrap/src/amazon/aws/codebuild/container/executor/main.go:16 +0x70
agentresources_build_1 exited with code 2
```

**Comment by subinataws** [comment]
This is resolved in the latest version of the local agent. SHA: 2fe3f77c8b580b82709e7f5f576313418eac2e5217a1da130ab1a8fb396f3ab2
