### ISSUE TITLE
Maven is outdated in openjdk-8 image

### ISSUE THREAD

**Issue by markuspeloquin** [aws/aws-codebuild-docker-images#84]
I was running a Maven build in CodeBuild, and I got the following:

```
1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.VersionRangeResolver
    for parameter 2 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultDependencyCollector
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.DependencyCollector
    for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  while locating java.lang.Object annotated with *
  while locating org.apache.maven.artifact.installer.DefaultArtifactInstaller
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
[backtrace]
```

Looking into the exception's message, it seemed to have something to do with an outdated Maven. In fact, the Maven version in the openjdk-8 image is 3.3.3. I upgraded the image to use 3.5.3 and my build succeeds.

**Comment by markuspeloquin** [comment]
Well, I thought that I was supposed to create an issue before the PR. You can tell this is my first time :)
